package com.avocent.dsview.net.snmp;

import static java.util.Collections.unmodifiableList;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>A base class that encapsulates all the information returned from ab invocation of a SNMP GET
 * on a particular SNMP agent</p>
 *
 *
 * Created by zshatzov on 4/19/2016.
 */
public abstract class SnmpResponse implements Serializable {
    protected final Integer clientId;
    protected final List<SnmpGetVariableBinding> variableBindings;
    protected final String requestId;
    protected final String errorStatusMessage;
    protected final int errorStatusCode;

    public SnmpResponse(Integer clientId, String requestId,
                        String errorStatusMessage, int errorStatusCode) {
        this.clientId = clientId;
        this.requestId = requestId;
        this.errorStatusMessage = errorStatusMessage;
        this.errorStatusCode = errorStatusCode;
        this.variableBindings = new ArrayList<>();
    }

    /**
     *
     * @return An ID setup by the client to correlate SNMP requests to SNMP responses
     */
    public Integer getClientId() {
        return clientId;
    }

    public void addVariableBinding(String oid, String value, String variableTpe){
        variableBindings.add(new SnmpGetVariableBinding(oid, value, variableTpe));
    }

    /**
     *
     * @return A unique ID generated by the SNMP API
     */
    public String getRequestId() {
        return requestId;
    }

    public List<SnmpGetVariableBinding> getVariableBinding(){
        return unmodifiableList(variableBindings);
    }

    /**
     *
     * @return An error ID constant as defined by the class <code>com.ireasoning.protocol.snmp.SnmpErrorStatus</code>
     */
    public int getErrorStatusCode() {
        return errorStatusCode;
    }

    /**
     *
     * @return A textual representation of an error message. For successful operations this field would the value <code>success</code>.
     */
    public String getErrorStatusMessage() {
        return errorStatusMessage;
    }
}
